export const FILTER = "FILTER";
export const RESET = "RESET";
export const ALL_VIDEOGAMES = "ALL_VIDEOGAMES";
export const CREATE_VIDEOGAME = "CREATE_VIDEOGAME";
export const VIDEOGAME_DETAIL = "VIDEOGAME_DETAIL";
export const VIDEOGAME_NAME = "VIDEOGAME_NAME";
export const CLEAR_DETAIL = "CLEAR_DETAIL";
